name: orion_safeguard
description: "Orion SafeGuard"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  bot_toast: ^4.1.3
  image_picker: ^1.1.2
  logger: ^2.5.0
  flutter_native_splash: ^2.4.5
  cached_network_image: 
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  permission_handler: ^11.4.0
  another_flushbar:
  intl: ^0.20.2
  sizer: ^3.0.5
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  file_picker:
  parse_server_sdk: ^8.0.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/png/
    - assets/icons/
    - assets/icons/svg/

  fonts:
    - family: DmSans
      fonts:
        - asset: assets/fonts/DMSans_24pt-Regular.ttf